//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace portfolio.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("portfolio.Resources.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Me.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s dive deep - ready to handle the pressure of technologically entrenched environments.
        /// </summary>
        public static string AltPhrase {
            get {
                return ResourceManager.GetString("AltPhrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Career.
        /// </summary>
        public static string Career {
            get {
                return ResourceManager.GetString("Career", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Stack Developer, QA Analyst,  2020 - today.
        /// </summary>
        public static string InfoCompumate {
            get {
                return ResourceManager.GetString("InfoCompumate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT analyst, Support, 2018 - 2020.
        /// </summary>
        public static string InfoPMVA {
            get {
                return ResourceManager.GetString("InfoPMVA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m coding C# everywhere. From creating custom controls and type libraries in legacy frameworks, to now reimagining them on the newest web based platforms..
        /// </summary>
        public static string IntroductionA {
            get {
                return ResourceManager.GetString("IntroductionA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;ve designed several services and ported them to Visual Basic winforms through COM interoperability, many involving advanced things like threads, non-native asynchronous code, and typed events. Also, I maintain a commercial softwarehouse website in ASP NET with MVC architecture and reusable Razor page components. Recently I built multiple minimal APIs from scratch, with features like authentication, dynamic routing, and built-in Swagger documentation..
        /// </summary>
        public static string IntroductionB {
            get {
                return ResourceManager.GetString("IntroductionB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today, most of my work is focused on developing with Blazor, while also leveraging knowledge in mobile projects using .NET MAUI Blazor Hybrid. I&apos;m also building our AI ecossystem with open-source tools and MCP..
        /// </summary>
        public static string IntroductionC {
            get {
                return ResourceManager.GetString("IntroductionC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LEARNING.
        /// </summary>
        public static string Learning {
            get {
                return ResourceManager.GetString("Learning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAIN.
        /// </summary>
        public static string Main {
            get {
                return ResourceManager.GetString("Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to launch — excited to explore the unknown and help shape the future of technology.
        /// </summary>
        public static string MainPhrase {
            get {
                return ResourceManager.GetString("MainPhrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m a pragmatic .NET developer — but above all, a person deeply bounded to computers. It was not even a choice;
        ///At 7 years old, already on this century, I had my first interaction with one: an Amiga, where I spent hundreds of hours playing Chuckie Egg.
        ///From that moment on, I began having countless experiences with digital technology throughout my childhood.
        ///
        ///Not long after that, I got an already-old Win95, where I started to manage things like Paint, Office, Printers, Local Network, and other tools — al [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Myself {
            get {
                return ResourceManager.GetString("Myself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  &quot;In the midst of the debate between OOP and functional programming, I embrace challenge-oriented programming&quot;.
        /// </summary>
        public static string Philosophy {
            get {
                return ResourceManager.GetString("Philosophy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLAYING.
        /// </summary>
        public static string Playing {
            get {
                return ResourceManager.GetString("Playing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right hand of Supreme Master of Universe.
        /// </summary>
        public static string RefCompumate {
            get {
                return ResourceManager.GetString("RefCompumate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Best trainee ever&quot; - Mr. Ribeiro.
        /// </summary>
        public static string RefPMVA {
            get {
                return ResourceManager.GetString("RefPMVA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rapidly got promoted from just helping ERP customers to QA department and backlog analysis.
        ///Right after that I was designing, coding, testing, publishing and maintaining that same software.
        ///In addition to developing, I&apos;m reference on SQL troubleshooting, Windows and IT infrastructure.
        ///My top responsabilities are API integrations, social communication services, AI and our website..
        /// </summary>
        public static string TextCompumate {
            get {
                return ResourceManager.GetString("TextCompumate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started teaching colleagues to deal with IT equipments, productivity tools and public sector ERP. 
        ///For the first time I coded a real page in a website using HTML, CSS and JavaScript and published it. 
        ///I also helped coordenate in core processes like biddings, approvals and requirements elicitation.  
        ///This was key to understand corporate relationships, team collaboration and end user perspective.
        ///.
        /// </summary>
        public static string TextPMVA {
            get {
                return ResourceManager.GetString("TextPMVA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work in progress.
        /// </summary>
        public static string Working {
            get {
                return ResourceManager.GetString("Working", resourceCulture);
            }
        }
    }
}
