name: Deploy

on: 
    push:
        branches: ["main"]
    workflow_dispatch:

permissions:
    contents: read
    pages: write
    id-token: write

concurrency:
    group: "pages"
    cancel-in-progress: false

jobs:
    deploy:
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-latest
        steps:
        -   name: Checkout
            uses: actions/checkout@v6

        -   name: Setup .NET
            uses: actions/setup-dotnet@v5
            with: 
                dotnet-version: 9.0.x

        -   name: Install .NET Wasm Tools
            run: dotnet workload install wasm-tools

        -   name: Restore dependencies
            run: dotnet restore

        -   name: Build
            run: dotnet build -c Release --no-restore

        -   name: Publish
            run: dotnet publish -c Release --no-logo

        -   name: Rewrite base href for GitHub Pages
            run: |
                REPO_NAME="${GITHUB_REPOSITORY#*/}"
                INDEX_FILE=$(find publish -name index.html | head -n 1)
                sed -i "s|<base href=\"/\" />|<base href=\"/${REPO_NAME}/\" />|g" "$INDEX_FILE"

        -   name: Add .nojekyll
            run: touch publish/wwwroot/.nojekyll

        -   name: Setup Pages
            uses: actions/configure-pages@v5

        -   name: Upload
            uses: actions/upload-pages-artifact@v4
            with:
                path: publish/wwwroot

        -   name: Deploy
            id: deployment
            uses: actions/deploy-pages@v4
                      